name: birds
description: "BirdsFeeder pet project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.1.1+9

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc_concurrency: ^0.2.5
  colorize: ^3.0.0
  file_selector: ^1.0.3
  flutter_appauth: ^8.0.1
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.14
  fluttertoast: ^8.2.8
  gal: ^2.3.0
  get_it: ^8.0.2
  intl: ^0.19.0
  just_audio: ^0.9.42
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5 # Native video dependencies.
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  system_theme: ^3.1.2
  timeago: ^3.7.0
  trackit: ^0.1.1+1
  trackit_console: ^0.2.0+3
  url_launcher: ^6.3.1
  web_socket_channel: ^3.0.1
  wakelock_plus: ^1.2.8

dev_dependencies:
  build_runner:
  dart_code_metrics_presets: ^2.18.0
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  husky: ^0.1.7
  intl_utils: ^2.8.7

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/png/
    - assets/mp3/

flutter_intl:
  enabled: true
  class_name: S
  main_locale: ru
  arb_dir: lib/l10n
  output_dir: lib/generated
